services:
  deadkashmenubundle.routing_loader:
      class: Deadkash\MenuBundle\MenuBundleLoader
      arguments: [@service_container]
      tags:
          - { name: routing.loader }

  deadkashmenubundle:
      class: Deadkash\MenuBundle\Service\BuildService
      arguments: [@service_container]

  deadkashmenubundle.twig.extension:
      class: Deadkash\MenuBundle\Twig\MenuExtension
      arguments: [ @service_container ]
      tags:
          - { name: twig.extension }